/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.itgate.detection_rec.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Locale;
import java.util.MissingResourceException;
import java.util.ResourceBundle;

import javax.swing.JOptionPane;

import com.itgate.detection_rec.db.Connexion;

public class PanelParametre extends javax.swing.JPanel {
public static ResourceBundle resourse;

    
         
 
   
    
    public PanelParametre() {
        initComponents();
         
          try {
            resourse = ResourceBundle.getBundle("Language",Locale.getDefault());
        } catch (MissingResourceException mre) {
      mre.printStackTrace();
        }
         

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        oldpasslbl = new javax.swing.JLabel();
        oldpasstxt = new javax.swing.JPasswordField();
        btnchange = new javax.swing.JButton();
        npasslbl = new javax.swing.JLabel();
        npasstxt = new javax.swing.JPasswordField();
        repasslbl = new javax.swing.JLabel();
        repasstxt = new javax.swing.JPasswordField();

        oldpasslbl.setText("Ancienne mot de passe");

        oldpasstxt.setText("jPasswordField1");
        oldpasstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldpasstxtActionPerformed(evt);
            }
        });

        btnchange.setText("Modifier mot de passe");
        btnchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchangeActionPerformed(evt);
            }
        });

        npasslbl.setText("Nouvelle mot de passe");

        npasstxt.setText("jPasswordField2");

        repasslbl.setText("confirmer mot de passe");

        repasstxt.setText("jPasswordField3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(repasslbl)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnchange)
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(oldpasslbl)
                            .addComponent(npasslbl))))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(oldpasstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(npasstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repasstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldpasslbl)
                    .addComponent(oldpasstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npasslbl)
                    .addComponent(npasstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(repasslbl)
                    .addComponent(repasstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnchange)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 313, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(527, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchangeActionPerformed
           

   
       

            oldpasslbl.setBounds(10, 60, 120, 20);
            oldpasstxt.setBounds(180, 60, 200, 25);
            npasslbl.setBounds(10, 90, 120, 25);
            npasstxt.setBounds(180, 90, 200, 25);
            repasslbl.setBounds(10, 120, 120, 25);
             repasstxt.setBounds(180, 60, 200, 25);
            btnchange.setBounds(180, 160, 120, 30);

            add(oldpasslbl);
            add(oldpasstxt);
            add(npasslbl);
            add(npasstxt);
            add(repasslbl);
           add (repasstxt);
            add(btnchange);

            btnchange.addActionListener((ActionListener) this);
        }

        public void actionPerformed(ActionEvent a) {
            if (a.getSource().equals(btnchange)) {
                int x = 0;
                
                String old = oldpasstxt.getText();
                String npassword = npasstxt.getText();
               String confirme = repasstxt.getText();
                try {
                    Connection con = null;
        Connection cn = Connexion.getConnection();
        {
                        Object repassword = null;
                        if (npassword.equals(old)) {
                            JOptionPane.showMessageDialog(this, "PASSWORD IS ALL REDY EXIST PLEASE CHOOSE OTHER PASSWORD");
                        } else if (npassword.equals(repassword)) {
                                    
                            cn = Connexion.getConnection();
                            PreparedStatement st;
                            st = con.prepareStatement("UPDATE createaccount SET password= '+npassword+' where cuser = 'cuser1'");
                            //                              st.setString(1, cuser);
                            st.setString(1, npassword);
                            st.executeUpdate();
                            JOptionPane.showMessageDialog(this, "PASSWORD UPDATE SUCCESSFUL");
                        } else {
                            JOptionPane.showMessageDialog(this, "PASSWORD NOT MATCH");
                            
                        }
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Query Not Executed");
                }
            }
        }

        public boolean vali(String cuser, String password) {
            boolean result = false;
            Connection con = null;
            try {
                Connection cn = Connexion.getConnection();
                PreparedStatement st;
                st = con.prepareStatement("select * from createaccount where cuser = ? AND password = ?");
                st.setString(1, cuser);
                st.setString(2, password);
                ResultSet rs = st.executeQuery();
                if (rs.next()) {
                    result = true;
                } else {
                    result = false;
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Query Not Executed");
            }
            return result;

        
    }//GEN-LAST:event_btnchangeActionPerformed

    private void oldpasstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldpasstxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldpasstxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchange;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel npasslbl;
    private javax.swing.JPasswordField npasstxt;
    private javax.swing.JLabel oldpasslbl;
    private javax.swing.JPasswordField oldpasstxt;
    private javax.swing.JLabel repasslbl;
    private javax.swing.JPasswordField repasstxt;
    // End of variables declaration//GEN-END:variables
}
